name: moli_menu
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.2.1+1
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  # json_serializable: ^6.8.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.2
  build_runner: ^2.4.12
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.12
  auto_route_generator: ^9.0.0
  freezed: ^2.5.7

flutter:
  uses-material-design: true
